### ISSUE TITLE
CTZ5 - OpenSourcing

### ISSUE THREAD

**Issue by Silmerias** [FrogSwarm/Citizen5#1]
Migration et amélioration de Citizen5 en OpenSource.

### ToDo
- [ ] Refacto du code
- [ ] Suppression de tout ce qui est hardcodé en variable d'env
- [ ] Containerization
- [ ] Ecriture des test unitaire github action
- [ ] Déploiement via github action
